import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import AddIcon from "@mui/icons-material/Add";
import Header from "../Components/Header";
import CreateNewDoc from "../Components/CreateNewDoc";
import { getSession, useSession } from "next-auth/react";
import Login from "../Components/Login";
import { Icon, IconButton } from "@mui/material";
import FolderIcon from "@mui/icons-material/Folder";

export default function Home() {
  const { data: session } = useSession();

  if (!session) return <Login />;

  return (
    <div className={styles.container}>
      <Head>
        <title>Google-Docs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="shadow-sm px-4 py-2 sticky z-10">
        <Header session={session} />
      </div>
      <section className="bg-gray-100 h-80">
        <CreateNewDoc />
      </section>
      <section>
        <div className="mx-auto max-w-4xl ">
          <div className="flex justify-between py-10">
            <div>
              <p>My Documents</p>
            </div>
            <div className="flex items-center">
              <p>Date Created</p>
              <div className="ml-5">
                <IconButton>
                  <FolderIcon />
                </IconButton>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
export async function getServerSideProps(context) {
  const session = await getSession(context);
  return {
    props: {
      session,
    },
  };
}
